#!/bin/sh

set -e

if [ "$1" = "configure" ]
then
	if ! getent passwd keystone > /dev/null 2>&1
	then
        adduser --system --home /var/lib/keystone --no-create-home --shell /bin/bash keystone
	fi
	chown keystone -R /var/lib/keystone /var/log/keystone
fi

# Automatically added by dh_installinit
if [ -e "/etc/init/keystone.conf" ]; then
	invoke-rc.d keystone start || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f keystone remove >/dev/null || exit $?
# End automatically added section

