/* ************************************************** */
/* Copyright (c) 2009, 2012 Cisco Systems, Inc.       */
/* All rights reserved.                               */
/* ************************************************** */
{
   "about":"About",
   "add_Users":"add Users",
   "administration":"Administration",
   "Administration":"Administration",
   "administration1":"Administration1",
   "administration2":"Administration2",
   "alarm_dashboard":"Alarm Dashboard",
   "alarms_page" : "Alarms",
   "alert_monitor":"Alert Monitor",
   "Alerts_and_Events_1":"Alerts and Events1",
   "Alerts_and_Events_History":"Alerts and Events History",
   "Another_Test_a_very_very_long_label_we_have_here":"Another Test a very very long label we have here",
   "Another_Test":"Another Test",
   "application_subtitle":"eXtensible Management Platform",
   "application_title":"Cisco Unified Solution",
   "applicationLogoImageAlt":"Cisco Systems Inc.",
   "auth_failed":"Invalid Username or Password. Please try again.",
   "Authentication":"Authentication",
   "Authorization":"Authorization",
   "Batch_Test":"Batch Test",
   "calender_cancel": "Cancel",
   "calender_save": "Save",
   "close_icon":"Close",
   "close_tooltip":"Close",
   "coast":" WestCoast",
   "configuration_page":"Configuration",
   "control_panel":"Control Panel",
   "copyright_Info":"©2012 Cisco Systems, Inc. Cisco, Cisco Systems and Cisco logo are registered trademarks of Cisco Systems, Inc. and/or its affiliates in the U.S. and certain other countries.",
   "copyright":"© 2012 Cisco Systems, Inc. Cisco, Cisco Systems and Cisco Systems logo are registered trademarks of Cisco Systems, Inc. and/or its affiliates in the U.S. and certain other countries",
   "Device_Credentials":"Device Credentials",
   "Device_Groups":"Device Groups",
   "device_inventory":"Device Inventory",
   "Device_Mgmt":"Device Mgmt",
   "Device":"Device",
   "Diagnostics":"Diagnostics",
   "diagonstic_view":"Diagnostic View",
   "Event_Customization":"Event Customization",
   "Event_Set_sub_1":"Event Set sub1",
   "Event_Set_sub_2":"Event Set sub2",
   "Event_Set_sub_3":"Event Set sub3",
   "Event_Sets":"Event Sets",
   "file_version":"Version: 0.1 (Dev Preview)",
   "Group_Management":"Group Management",
   "help":"Help",
   "host_name":"Hostname",
   "image_close_title":"Close",
   "image_pushpin_title":"Pin",
   "invalid_credentials":"Invalid Username or Password. Please try again.",
   "inventory_page":"Inventory",
   "ip_adress":"IP Address",
   "IP_Phone_Status":"IP Phone Status",
   "IP_Phones_and_Applications_a_very_long_label_we_have_here":"IP Phones and Applications a very long label we have here",
   "key_1":"License Type",
   "key_2":"Device Count",
   "key_3":"Install Date/Updated On",
   "key_4":"Expiry Date",
   "label_alarm":"Alarm",
   "label_Prefer":"Preferences",
   "label_Profile":"Profile",
   "lastUpdated":"Last Updated:",
   "logged_out_inactivity":"You have been logged out due to inactivity.",
   "logged_out":"You have been successfully logged out.",
   "login_button":"Log In",
   "logout":"Log Out",
   "Manage_Views":"Manage Views",
   "maxlimitcrossed":"User is locked. Please reset the password",
   "monitor_page": "Monitor",
   "Monitoring":"Monitoring",
   "Node_to_Node_Test":"Node to Node Test",
   "Notification_Criteria":"Notification Criteria",
   "Notifications":"Notifications",
   "Overview":"Overview",
   "password_expired":"Your password is expired. Click the 'Problems logging in?' ",
   "password_required":"Password is required!",
   "password":"Password",
   "Personalized_Report":"Personalized Report",
   "Phone_Status_result":"Phone Status result",
   "pindown_icon":"Pin down",
   "Policy_Elements":"Policy Elements",
   "Polling_and_Thresholds_1":"Polling and Thresholds1",
   "Prefrences":"Preferences",
   "problems_logging":"Problems logging in?",
   "product_family_name":"Cloud Services",
   "product_name":"Cloud Management Platform",
   "provisioning_page":"Provisioning",
   "remember_username":"Remember username",
   "Reports":"Reports",
   "Service_Quality_Alerts":"Service Quality Alerts",
   "Service_quality_History":"Service quality History",
   "session_expired_duplicate":"This session has been expired, possibly due to multiple concurrent logins being attempted as the same user.",
   "session_expired":"Your session has expired.",
   "sites_page": "Sites",
   "sliderClose":"Close",
   "sliderPullDown":"Pull down",
   "sliderPullOut":"Pull out",
   "sliderPullUp":"Pull up",
   "Some_Test":"Some Test",
   "support":"Support",
   "Switch_User":"Switch User",
   "Synthetic_Test":"Synthetic Test",
   "top_message":"Message Icon",
   "topology_page":"Topology",
   "usermanagement_page":"User Management",
   "username_required":"Username is required!",
   "username":"Username",
   "value_1":"Evaluation",
   "value_2":"100",
   "value_3":"28 Jun 2012",
   "value_4":"28 Jun 2012",
   "Video_Phones":"Video Phones",
   "virtualdomain":"Virtual Domain: ",
   "login_page_ok": "OK"
}